# Generated by Django 3.2.13 on 2022-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='events',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
