# Generated by Django 3.2.13 on 2022-07-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_piid',
            new_name='stripe_pid',
        ),
    ]
