# Generated by Django 3.2.13 on 2022-05-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220527_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='extra_cat',
            field=models.CharField(max_length=254),
        ),
        migrations.DeleteModel(
            name='ExtraCat',
        ),
    ]
