# Generated by Django 3.2.13 on 2022-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220530_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='extra_cat',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
