# Generated by Django 3.2.13 on 2022-07-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rrp',
        ),
    ]
