# Generated by Django 3.2.13 on 2022-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_rrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
